# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  run:
    cmds:
      - cargo run -q
  watch:
    cmds:
      - cargo watch -x run
  build:
    cmds:
      - cargo build
  release:
    cmds:
      - cargo build --release
  docker-build:
    cmds:
      - docker build . -t rust-starter
  docker-run:
    cmds:
      - docker run rust-starter
    silent: true
